// Member roster for Legends chapter — Regional Conclave 2026
const MEMBERS = [
  "Abhishek Sinha",
  "ANIL DENGWANI",
  "Anshul Kankaria",
  "Anshuman Sharma",
  "ASHISH GUPTA",
  "Deep Patel",
  "Devesh Bairagi",
  "Dhananjay Karanjgaokar",
  "Gopal Agrawal",
  "Hemant Goyal",
  "Kaniyha Agarwal",
  "Kavya More",
  "Manish Sharma",
  "Mayank Jain",
  "Mohammad Imran",
  "Mohit Ram Sen",
  "Naveen Jiwnani",
  "Nayan Patel",
  "Nikhil Agrawal",
  "Nitin Khoobchandani",
  "Nitin Sharma",
  "Parul Sharma",
  "Prateek Suktel",
  "Rakhee Rakesh",
  "Rashmi Agrawal",
  "Sanjay Hinduja",
  "Shantanu Agrawal",
  "Shubham Naidu",
  "Suyash Tiwari",
  "Vijay Chandravanshi",
  "Vinay Deshlahara",
  "Vinit Singh",
  "Virendra Kumar Sahu",
  "Yash Nagdeo",
  "Yougantar Choubey",
  "Narendra Kumar sahu",
  "Yeshwant Yadv",
  "JYOTI JAIN",
  "RAJ Khelwani",
  "Mohammad Hasnain Raza",
];
