// Member roster for Gladiators chapter — Regional Conclave 2026
const MEMBERS = [
  "Abhishek Khandelwal",
  "Abhishek Shukla",
  "Aditya Raaj Manikpuri",
  "Adv Devbrat Sharma",
  "Ajay Kumar Chawlani",
  "Ajay Patel",
  "AKASH THAKUR",
  "Amit Shriwas",
  "Anant Bagdiya",
  "Anil Bhardwaj",
  "Anil Chandrakar",
  "Ankit Baid",
  "Anup Agrawal",
  "Anurag Khandelwal",
  "Ashish Kedia",
  "Ashutosh Pandey",
  "Avishek Agrawal",
  "Bhupendra Singh",
  "Bunty Malani",
  "CHIRAG Doshi",
  "Debasish Agrawal",
  "Deepak Bajoria",
  "Deepak Chourasiya",
  "Deepak Patel",
  "DEVENDRA SAHU",
  "Divyam Gupta",
  "Dr. Dinesh Shrey",
  "Ganga S Agrawal",
  "Ghanshyam Das Kotwani",
  "HARI KRISHNA",
  "HARJINDER SINGH GUMBER",
  "Himanshu Bondia",
  "Jayant Khandelwal",
  "JUBILEE MADURADAS",
  "Jyoti Kalwani",
  "KANHA AGRAWAL",
  "KARAN TAMBOLI",
  "KRISHNA PATEL",
  "Kritisha Agrawal",
  "Kshitij Pandey",
  "Lala Sinha",
  "Manish Barmaiya",
  "Manjinder Singh Sandhu",
  "Mitesh Chand",
  "MUKESH JHA",
  "Mukesh Naulakha",
  "Mukund Singh Thakur",
  "Munish Srivastava",
  "Neeraj Singh",
  "Pradeep Vishwakarma",
  "Prakhar Chhajed",
  "Pranav Budhdeo",
  "Prashant Maurya",
  "Rahul Verma",
  "Ram Sahu",
  "Ramani Bhavik Patel",
  "Rohit Sharma",
  "RUPALI SAHU",
  "Sachin Asai",
  "Sachin Khandelwal",
  "Sagar Bajaj",
  "SANDEEP SINGH",
  "Sanjana Mishra",
  "Saurabh Gupta",
  "Shailesh Parmar",
  "Shekhar Singh Patel",
  "Shiv Prakash Singh",
  "Shivraj Suthar",
  "SHOURYA VARDHAN MIRANIYA",
  "Siddhant Dubey",
  "Sohan Bajaj",
  "Somesh Agrawal",
  "Sonam Agrawal",
  "Sudhir Nirmalkar",
  "Sushank Agrawal",
  "Tejas Baid",
  "Vandan Pandey",
  "Vinit Tiwari",
  "Vishal Agrawal",
  "Yash Agrawal",
  "YASH RAJ SINGH",
  "Yatendra nath Singh",
  "Anupam Vaishnav",
  "Meghraj Sahu",
  "Arpit Aabhas Isaac",
  "Gourav Jain",
  "Prabhat Sinha",
  "Vinay Adil",
  "Gaurav kumar Sahu",
  "Akash Agrawal",
  "Tushar Jain",
  "Amrish Sharma",
  "SANTOSH Kumar Kumhar",
  "Rohit Banjare",
];
