// Member roster for Hallmark chapter — Regional Conclave 2026
const MEMBERS = [
  "Agamya Shrivastava",
  "AISHWARY DEV SINGH",
  "Ajay Sahu",
  "Amit Chhabria",
  "Amit Sharma",
  "ANSHUL AGRRAWAL",
  "Asfiya Khan",
  "Ashish Chauhan",
  "Ashish Khemani",
  "Ashish Raul",
  "Ashutosh Agrawal",
  "Ashutosh Onkar",
  "Avinash Khetpal",
  "Bhavesh Thakkar",
  "CA Paras Bhansali",
  "Chandrakant Dewangan",
  "Dibyendu Chakravarty",
  "Dipti Kumar Nayak",
  "GHANSHYAM SINHA",
  "Gulshan Kumar",
  "Himanshu Sahu",
  "Jaduvansh Sharma",
  "Jasmeet Singh",
  "Kanishka Parihar",
  "KARANJIT SINGH",
  "Kartik Dewangan",
  "Meghnath Dhrruv",
  "Mohanish Pushpakar",
  "Neeraj Sharma",
  "Nikhil Sahu",
  "Om Prakash Choyal",
  "Parakram Singh",
  "Pranav Agrawal",
  "Preeti Barman",
  "Rahul Gupta",
  "Rahul Mangwani",
  "Rajesh Arya",
  "Ravi Andani",
  "Ravi Jaisinghani",
  "Ravi Sachdev",
  "Ravi Thakur",
  "Ravi kumar Tuli",
  "ROSHAN LAL NISHAD",
  "SAMEER JAISWAL",
  "Sanjeev Shekhar Sahu",
  "Shyam Singhaniya",
  "Sona Kale",
  "Sourabh Sahu",
  "Sunil Jagyasi",
  "Sunita Jadwani",
  "Suresh Kumar Katewar",
  "Sushant Soni",
  "T Srinivas Rao",
  "TAJINDER SINGH SAINI",
  "Tikku Sahu",
  "TRILOCHAN SAHU",
  "Umang Bhawnani",
  "Vansh Arora",
  "Vinay Kumar Rana",
  "Vinod Kumar Sharma",
  "Vinod Kumar Jain",
  "Yash Gidwani",
  "Yashwant Verma",
  "Sulochna Soni",
  "Anil jotsinghani",
  "Ashish Khandelwal",
];
