// Member roster for Icons chapter — Regional Conclave 2026
const MEMBERS = [
  "Abhay Nathani",
  "Aditya Singh Surana",
  "Ajay Agrawal",
  "AKHILESH AGRAWAL",
  "Aman Agrawal",
  "Aman Garg",
  "Anish Goel",
  "Ankit Jain",
  "Arjun Arawalia",
  "ASHISH BERLIA",
  "Ashok Kumar Verma",
  "Ayush Agrawal (Adv)",
  "Ayush Agrawal (TMT)",
  "CHHATRAPAL VERMA",
  "Deepak Kumar Jain",
  "Dinesh Jain",
  "Dinesh Roy",
  "Disha Agrawal",
  "Gagan Kasliwal",
  "Gurusharan Singh Chadha",
  "Hardik Rathod",
  "Hemant Kumar",
  "Himanshu Jain",
  "JITENDRA VERMA",
  "Kanak Kaushik",
  "Kapil Sahu",
  "Kirti Patel",
  "Krishna Agrawal",
  "Lekhhak MUKIIM",
  "Manish Bose",
  "Mayank Patel",
  "Nagesh Sahu",
  "Nikhil Mishra",
  "Nipesh Prajapati",
  "Nishant Sahu",
  "Nitin Bachhawat",
  "Nitin Khetpal",
  "Piyush Goklani Goklani",
  "Prabhjot Singh",
  "Prakhar Goyal",
  "Ravi Kumar Singh",
  "Ritu Gupta",
  "RK Gandhi",
  "Rohit Agrawal",
  "Roshan Singh",
  "Samyak Jain",
  "Sandeep Das",
  "Sanidhya Jain",
  "Sarbhav Mittal",
  "Siddharth Goyal",
  "Sourabh Agrawal",
  "Srivastava Chauhan",
  "Sumeet Soni",
  "Sunny Bansal",
  "Vasu Iyengar",
  "Vikas Yadu",
  "Kaushik Katta",
  "Somesh Agrawal",
  "Manish Bajoria",
  "Bhupendra Jain",
  "Roshan Mohata",
];
