// Member roster for Amigos chapter — Regional Conclave 2026
const MEMBERS = [
  "Abhas Agrawal",
  "Ajay Tharwani",
  "Ajinder Singh Saluja",
  "Amit Agrawal",
  "Amitabh Agrawal",
  "Aniket Sahu",
  "ANIMESH TIKARIHA",
  "Anjali Minocha",
  "Anmol Jeevan",
  "Arjun Gupta",
  "Ashutosh Agrawal",
  "Ayush Yadav",
  "CA AYUSH GOYAL",
  "DAMYANTI PRABHA GUPTA",
  "Hardeep Singh Hora",
  "Harshal Verma",
  "Hemant Badwani",
  "Hemant Raichura",
  "Hussain Vana",
  "Inderpal Singh Rana",
  "Ishaan Saha",
  "Ishdeep ARORA",
  "JASVINDER SINGH",
  "KAJAL MANDHANI MANDHANI",
  "Karnika Patnaik",
  "KUNAL RELWANI",
  "Lavya Sundrani",
  "Lokesh Sodha",
  "Manish Bhutada",
  "Manish Kumar Rathore",
  "Manisha Chowbey",
  "Manmeesh Kaur Rajpal",
  "MEGHNA SAHANI",
  "Milan Patel",
  "Mohit Lulla",
  "Mohit Manik",
  "Navin Agrawal",
  "Neeraj Agrawal (LED Signage)",
  "Neeraj Agrawal (Wooden Doors)",
  "Neha Wadhwa",
  "PANKAJ AGRAWAL",
  "Poonam Sharma",
  "Prakhar Jain",
  "Prapan Jain",
  "Pulkit Khandelwal",
  "Puneet Bapna",
  "RAHUL JADHAV",
  "Rahul Jhabak",
  "RAJAT JAIN",
  "RAJENDRA KR SAHU",
  "Rajesh Mehta",
  "RAJESH . SAHU",
  "RATAN AGRAWAL",
  "Raveena K Bhui",
  "Ritik Agarwal",
  "Rohit Kanoi",
  "Sambhav Daga",
  "Satbir Juneja",
  "Satish Kumar Kashyap",
  "Saurabh Patil",
  "SHAILENDRA LATH",
  "SHAILESH PATEL",
  "Shiv Agrawal",
  "SHIVCHARAN LAL SAHU",
  "Shreyansh Sankhla",
  "Shubham Agrawal",
  "Simran Virani",
  "Somen Bhowmick",
  "Subodh Toley",
  "Sumer Jatav",
  "Sumit Sablani",
  "Vaibhav Dedhe",
  "Vaibhav Khandelwal",
  "VASANT PATEL",
  "Vicky Janghel",
  "Vijit Goyal",
  "Vishal Agrawal",
  "Vishal Motwani",
  "Vivek Sharma",
  "Yogen Agrawal",
  "Kapil Makhija",
  "nikhil Wadhwani",
];
