// Member roster for Diamond chapter — Regional Conclave 2026
const MEMBERS = [
  "Abhishek Agrawal",
  "ABID Memon",
  "Ajay Kumar Sahu",
  "Alok Kumar Tiwari",
  "Aman Mahanand",
  "Amitesh Sharma",
  "Arun Sahu",
  "Arvind Kumar Yadav",
  "Ashish Sakarkar",
  "Ashish Somani",
  "Avinay Kumar Dubey",
  "Ayush Poddar",
  "DEEPAK SANODIYA",
  "DEEPESH CHHABRA",
  "DEVENDRA KR CHANDRAKAR",
  "Dr Syed Abdul Wahid",
  "Dr. Pradeepa .",
  "Gaurav Agrawal",
  "GOVIND YADAV",
  "Himanshu Sawariya",
  "Jagannath Reddy",
  "Jain Vikash SIPANI",
  "Jeet Sherwani",
  "Jitendra Sahu",
  "Kailash Chand Jangid",
  "Kishor Kumar Sahu",
  "Mamta Parakh",
  "Manish Fulekar",
  "Manish Goyate",
  "MANISH SINGHI",
  "MANOJ BORADE",
  "Mohammad Shakeel",
  "Mohit Harjpal",
  "NARENDRA SINGH THAKUR",
  "Naveen Balivada",
  "Navneet Singh Kambo",
  "NITIN AGRAWAL (AGRICULTURE LAND)",
  "NITIN AGRAWAL (HOME FURNISHING)",
  "Pooja Agrawal",
  "Pranav Verma",
  "Prashak Kumar Goyal",
  "Pulkit Goel",
  "RADHEYSHYAM SHARMA",
  "Rahul Sharma",
  "Ramesh Patel",
  "Romy Vohra",
  "SANDEEP DAGA",
  "Sanjay Dewangan",
  "Santosh Duggar",
  "Satyendra Shukla",
  "Saurabh Swarnakar",
  "SHAILESH JAIN",
  "Shubham Dewangan",
  "Sumit Gurbani",
  "SUSHIL BENGANI",
  "T G Sanjeev Kumar",
  "Taniyaa Om Sinhaa",
  "UMANG SHRIVASTAVA",
  "VAISHAKH KUSRE",
  "VIKAS PARAKH",
  "Vishal Nankani",
  "Yash Wadhwa",
  "Asmat Khan",
  "CHIRAG GANGWANI",
  "Ravindra Vyas",
  "Kishan Chaudhary",
];
