// Member roster for Karma chapter — Regional Conclave 2026
const MEMBERS = [
  "Aman Sahu",
  "Amber Sahu",
  "Amit Nagdeo",
  "Animesh Makhija",
  "Anmol Agrawal",
  "Arpit Maheshwari",
  "BHANU PRATAP SINGH MOYAL",
  "Giriraj Shrivas",
  "Jeetesh Parwani",
  "Jitesh Balani",
  "Kirtan Jindal",
  "Krishna Sinha",
  "Likhesh kumar Jayswal",
  "Lokendra Sinha",
  "MITHLESH NIRMALKAR",
  "Munira Zar",
  "Pramod Pandey",
  "Rahul Tiwari",
  "RAKESH GUPTA",
  "Ravi Godwani",
  "Ritik Baid",
  "Sachin Malani",
  "Sangeeta Singh",
  "Sanjay Ashani",
  "SHARAD ROKADE",
  "Shreyans Parakh",
  "Sneha Shobhwani",
  "Suryakant Sharma",
  "Vaibhav Sachdev",
  "Vaishali Virani",
  "Yogesh Shukla",
  "Yogesh Kumar Chainani",
  "Raunak Maheshwari",
  "Lavish Pritwani",
  "Alif Memon",
  "Amit Jaiswal",
  "Montu Kumar",
  "Shikhar Agrawal",
  "Mehal Parakh",
];
