// Member roster for Tycoons chapter — Regional Conclave 2026
const MEMBERS = [
  "Abhishek Goel",
  "Akash Kumar Vishwakarma",
  "Amit Kumar Parmar",
  "Amit Prajapati",
  "Anish Juneja",
  "Ar. Asavari Mohdiwale",
  "Bhupendra Sharma",
  "CA Mayank Kesharwani",
  "Chandan Kumar Nishadraj",
  "Diksha Kiri",
  "Dishaa M Ramani",
  "Girish Agrawal",
  "HARIKRISHNA NAHAK",
  "Hirendra Varma",
  "HITESH PANJWANI",
  "Kushal Patel",
  "Manish Agrawal",
  "Mohammed Husain",
  "NIKHIL JASUJA",
  "Nitesh kumar Jain",
  "Piyush Gidwani",
  "Purushottam Kiri",
  "Rahul KHOOBCHANDANI",
  "Rakesh Kalwani",
  "Ravinder Ubeja",
  "Ritesh Doshi",
  "Roshail Agarwal",
  "Samrath Singh Gumber",
  "Sanu Agrawal",
  "SEEMA AGRAWAL",
  "Shailesh Kumar Soni",
  "Shekhar Sachdev",
  "Siddharth Das",
  "Somya Sinha",
  "Sunny Asai",
  "Surbhi Verma",
  "Suyog Agrawal",
  "TUSHAR THAWRANI",
  "Utkarsh Agrawal",
  "Vansh Patel",
  "Vinod Kumar Mishra",
  "Vyas Narayan Dewangan",
  "Gopal Kanoje",
  "Achal Kedia",
  "Jayesh Panjwani",
  "Mohit Roopchandani",
  "Ishu Verma",
  "Rahul Sultania",
  "OM LAHRE",
];
