// Member roster for Alpha chapter — Regional Conclave 2026
const MEMBERS = [
  "Aakash Agrawal",
  "AASHISH AGRAWAL (Security)",
  "Abhilash Patnaik",
  "Ajay Singhania",
  "Ajay Kumar Kedia",
  "Akash Sharma",
  "AKSHAY KUMAR HOTA",
  "Alok Jindal",
  "Aman Agrawal",
  "Amit Mittal",
  "Anal Jain",
  "ANAND SHARMA",
  "Anish Chhabra",
  "Ankit Chawla",
  "Ankit Kumar Agrawal",
  "Anshul Agrawal (PVC Panels)",
  "Anuj Gupta (Restaurant)",
  "Anurag Bansal",
  "Arif Khan",
  "ASHISH AGRAWAL (Home Appliances)",
  "Ashu Airan",
  "Atharva Mittal",
  "Atul Agrawal",
  "Awant Agrawal",
  "Ayush Modi",
  "Bhojraj Vishwakarma",
  "BHUVANESHWAR VISHAL",
  "CA Amit Agrawal",
  "Chandramani Behera",
  "Deepak Agrawal",
  "Deepak Arora",
  "Deepak Kumar Saw",
  "Dev Dhariwal",
  "Dew Kumar Patel",
  "Gaurav Modi",
  "Girdhar Borkar",
  "GOPAL PATEL",
  "Harsh Khirwal",
  "HEMANT PATEL",
  "Jawahar Motwani",
  "Kamal Agrawal",
  "Kamlesh Agrawal",
  "Kamlesh Motwani",
  "Kiran Sahu",
  "Manish Jaiswal",
  "Manoj Agrawal (CCTV)",
  "Manoj Agrawal (PHARMACIST)",
  "Manoj Mittal",
  "MONU AGRAWAL",
  "Mukesh Agrawal (Hydraulic Rubber Hose)",
  "Nand kishor Agrawal",
  "Naveen Jindal",
  "Navish Agrawal",
  "Nikhil Agrawal",
  "Nitish Thakur",
  "Pawan Kumar Singh",
  "Piyush Parmar",
  "Poonam Siingh",
  "Prakash Agrawal",
  "Prince Sahu",
  "Raj Sehgal",
  "Rajnayan Haripriya",
  "Ram Parkash",
  "RG Nayak",
  "Sahil Agrawal",
  "Saksham Singhal",
  "SANDEEP AGRAWAL",
  "Sandeep Swarnakar",
  "SANJAY GOYAL",
  "SARAS GOYAL",
  "Satya Sahu",
  "Saurabh Gupta",
  "Shubham Goyal",
  "Shyam Kumar Namdeo",
  "Sneha Chetwani",
  "Sumit Singh Wadhwa",
  "Suyash Ambuwani",
  "Umesh Kumar Thawait",
  "Vibha Jaiswal",
  "Vikas Agrawal",
  "Vikas Modi",
  "Vikash Agarwal",
  "Vinay Agrawal (Food Hampers)",
  "VINAY SHUKLA",
  "Vinay Kumar Agrawal (Roofing Sheets)",
  "Vinod Kumar Rajgond",
  "Yash Chopra",
  "CHANDAN JAGATRAMKA",
  "Animesh Goyal",
  "Pratik Garg",
  "DR Yogesh Patel",
  "Mukesh Kumar Agrwal",
  "Ansh Mittal",
  "Sourabh Shrivastava",
  "SANTOSH KUMAR NAIK",
  "SHIVAM SINGH DUREJA",
  "DR. SATISH AGRAWAL",
  "PARVINDAR SINGH RAJPAL",
  "DEVENDRA SINGH MALHOTRA",
  "NIKHIL PATEL",
];
