// Member roster for Billionaires chapter — Regional Conclave 2026
const MEMBERS = [
  "Aashish Sultania",
  "Abhishek Agrawal",
  "ABHISHEK NARAD",
  "Ajay Swarnkar",
  "Amar Agrawal",
  "Anand Agrawal",
  "Ankita Soni",
  "Anshu Agrawal",
  "Aparna Singh",
  "Ashutosh Agrawal",
  "Ashutosh Agrawal (Ladies wear)",
  "AYUSH AGRAWAL",
  "Bhupendra Singh Gandhi",
  "Deepak Agrawal",
  "Dinesh Soni",
  "Harvinder Singh",
  "Hoslaa Agrawal",
  "Jai Prakash Manwani",
  "Kishore Kumar Agrawal",
  "KRISHNA AGRAWAL",
  "Maheshwar Sharma",
  "Manish Jaiswal",
  "Manoj Agrawal",
  "Manoj Kumar Jesrani",
  "Md Azaz Shekhani",
  "Mehul Agrawal",
  "Mohit Ohri",
  "Naveen Kumar Agrawal",
  "Neeraj Mishra",
  "Nitin Gupta",
  "NITIN SABHARWAL",
  "Om Jaiswal",
  "Parneet Singh",
  "PRABHJOT SINGH ANAND",
  "PRANJAL AGRAWAL",
  "Pranshu Agrawal",
  "Prashant Agrawal",
  "Prateek Modi",
  "Pratik Jain",
  "Praveen Jakhadi",
  "PRIYANK KUMAR AGRAWAL",
  "Pulkit Agrawal",
  "Raj Agrawal",
  "Raja Agrawal",
  "Rajesh Milan",
  "Ravi Lalwani",
  "Rinkle Agrawal",
  "Ritesh Agrawal",
  "Ritesh Pinjani",
  "Ritik Goyal",
  "Rupesh Agrawal",
  "Sagar Juneja",
  "SAGAR MAKHIJA",
  "Sagar Sachdev",
  "Sangeet Agrawal",
  "Shashi Agrawal",
  "Shikha Sharma lamba",
  "SHRAWAN AGRAWAL",
  "Shubham Agrawal (Industrial Gases)",
  "Shyam Singh",
  "Sitanshu Agrawal",
  "Sohan Agrawal",
  "Sourabh Gupta",
  "Subhash Gupta",
  "SUMIT AGRAWAL",
  "SWAPNIL KHARE",
  "Ujjwal Singhania",
  "Vaibhav Silla",
  "Vandana Raja Shah",
  "Vansham Khubchandani",
  "Vikas Agrawal",
  "VIKRAM AGRAWAL",
  "Vipul Agrawal",
  "Yuvraj Rathore",
  "Ganesh Modi",
  "Meenket Sahu",
  "AASHISH TILWANI",
  "Sandeep Kumar Agrawal",
  "Aman Modi",
  "Kriti Panjwani",
  "Utkarsh Agrawal",
  "Taranjeet Singh",
];
