// Member roster for Champions chapter — Regional Conclave 2026
const MEMBERS = [
  "Aanchal Jain",
  "Aastha Verma",
  "Abhay Gupta",
  "Abhishek Dewangan",
  "Abhishek Pratap Singh",
  "Ajay Agrawal",
  "Akhil Maediratta",
  "Albert Kujur",
  "Ali Asgar Attar",
  "Alok Rajkotia",
  "Amar Kumar",
  "Amit Agrawal",
  "AMIT BALWANI",
  "Amit Mahansaria",
  "Anand Parchani",
  "Anil Singh Chauhan",
  "Arjun Singh",
  "Aruna Singh Parihar",
  "Ashish Chandrakar",
  "ASHISSH AGGRAWAL",
  "Ashok Anandani",
  "Bhartesh Padhiar",
  "Bhavesh Nichlani",
  "Chatar Singh Saluja",
  "Chudamani Pradhan",
  "Deepak Goyal",
  "DEEPAK GUPTA",
  "Deepak Kumar",
  "Dev Jasuja",
  "Devesh Wahne",
  "Dinesh Patel",
  "Dipsi Rajpoot",
  "Dr Ajit Varwandkar",
  "Dr Akhilesh Sahu",
  "Dr Resham Das",
  "Dr. Jitendra Saraf",
  "Gaurav Agrawal",
  "Gaurav Lunia",
  "GAURAV SINGH RAJPUT",
  "Gopal Dulhani",
  "Gurteg Singh",
  "Hardik Patel",
  "HARDIK ROKAD",
  "Harjinder Singh Sodhi",
  "Harpreet Singh",
  "HARPREET SINGH (AUTOMOBILE)",
  "Harsheet Kaur",
  "JAI THARANI",
  "Jay Agrawal",
  "JAYANT JAIN",
  "Jayant Patel",
  "Jesal Shah",
  "Jitendra Sinha",
  "Kamal Kishor Agrawal",
  "Kevin Patel",
  "Kranti Kumar",
  "Kunal Jain",
  "Kushal Ujala",
  "Lakshya Jain",
  "Laxmi Paikara",
  "LAXMIDATTA BAJPAYEE",
  "Madhavi Shukla",
  "Manish Agrawal (G)",
  "Manish Agrawal (P)",
  "MANISH JAIN",
  "MANISH MAKHIJA",
  "Manish Patel",
  "MANISH SINGHAL",
  "Mayank Agrawal",
  "Mitesh Bhanushali",
  "MOHAMMAD AAMIR",
  "Moonmoon Agrawal",
  "Murtaza Ziya",
  "NARENDRA SINHA",
  "NAVEEN GOYAL",
  "NAVIN SHARMA",
  "Niket Agrawal",
  "Niket Mehta",
  "Nikhil Agrawal",
  "Nimmisha Soni",
  "Nishant Bafna",
  "Nitesh Agrawal",
  "Pradeep Manek",
  "Prakash Rana",
  "PRAKASH. AGRAWAL",
  "Prakhar Agrawal",
  "Pramod Shrivastava",
  "Pranay Khandelwal",
  "Prashant Inchulkar",
  "Prashant Mahto",
  "Pratik Patel",
  "Pratyush Channawar",
  "Priyanka Singh",
  "Raghuraj Singh Bisen",
  "Rajender Singh",
  "Ravindra Saraf",
  "Ritesh Gupta",
  "Ritesh Khandelwal",
  "ROSHAN AGRAWAL",
  "Sahil Yadav",
  "Samkit Jain",
  "Sandeep Kumar Rajput",
  "Sandeep Makhija",
  "SANJANA CHHABDA",
  "Sankalp Varvandkar",
  "Santosh Ahuja",
  "Saurabh Jain",
  "SHANKH AGRAWAL",
  "Shreeji Prakash Agrawal",
  "Shweta Jain",
  "Shyam Gattani",
  "Siddharth Chitlangia",
  "SUBHASH SINGH",
  "Sumit Sharma",
  "Sunil Sharma",
  "Viinita Saxena lenpale",
  "VIKAS KUMAR SAHU",
  "Vinay Singh",
  "VINAY SIPANI",
  "Vinay Kumar Shreerangam",
  "Vishal Shah",
  "Yash Kumar Sahu",
  "Abhinit Upadhyay",
  "Omkar Dewangan",
  "Hrishabh Soni",
  "Vaibhav Jain",
  "RAHUL Agrawal",
  "Soniya Gour",
  "Akash Agrawal",
    "Yash Agarwal",
    "Akash Choudhury",
    "Divya Bajaj",
];
