// Member roster for Barons chapter — Regional Conclave 2026
const MEMBERS = [
  "ABHINAV DAS",
  "ABHISHEK BARADIA",
  "Ajay Oswal",
  "Ajay Prathyani",
  "Akash P Jadwani",
  "Akhilesh Pandey",
  "ALPESH SHAH",
  "Amar Jaswani",
  "Anil Parichha",
  "Anjana Modi",
  "Anmol Kedia",
  "Anshul Jain",
  "Arpit Jain",
  "Arpit Jain....",
  "Ashmeet Kaur Tuteja",
  "Ashok Yadav",
  "AYUSH BHAUKA",
  "Bishwajit Chakraborty",
  "Dilip Patel",
  "Dilshad Ansari",
  "Dinesh Athwani",
  "ERIC THEOPHILUS",
  "Gaurav Dhadiwal",
  "Gaurav Goel",
  "Girdhari Deep",
  "Girish Mirani",
  "Harshada Tichkule",
  "Harshdeep Singh Gumber",
  "Harshit Agrawal",
  "Himanshu Andani",
  "Himanshu Goyal",
  "HITESH PATEL",
  "JATIN JAIN",
  "Jaya Arora",
  "KAMAL KRISHNANI",
  "LALIT RATHI",
  "Manish Khandelwal",
  "Mayur Thakkar",
  "Mehul Patel",
  "Mohammad Asif Ganj",
  "Murtaza Dodiya",
  "Nandlal Agarwal",
  "Neeraj Tiwari",
  "Nikhil Golchha",
  "Nilesh Shah",
  "Nishikant Gupta",
  "NITYAM CHOPDA",
  "Pankaj Agrawal",
  "Pankaj Bajaj",
  "Pankaj Jain",
  "Pranay Jain",
  "Prashant Soni",
  "Prateek Tayal",
  "PREET AHUJA",
  "PUSHP DAGA",
  "Randeep singh Chadha",
  "Rishabh Raj Shrivastav",
  "Ritesh Wadhwa",
  "Rohit Saxena",
  "Sanjog Jhabak",
  "SATYA PRAKASH SINGH",
  "SAURABH AGRAWAL.",
  "Shaan Muhammad Saifi",
  "Shrenik Jain (LP)",
  "Shreyans Jhabak",
  "Shubham Jain",
  "Siddharth Dani",
  "Sidharth Khandelwal",
  "Siya Jaswani",
  "Sourabh Patel",
  "Sourav Malani",
  "SUJEET CHOURASIA",
  "Sumeet Balwani",
  "Sumeet Kothari",
  "Suparshva Jain",
  "SUSHANT BANSOD",
  "SWAPNA SHRIRANGAM",
  "Tushar Agarwal",
  "Ujwal Jain",
  "Vikash Sharma",
  "Vinesh Gupta",
  "Vinit Pathak",
  "Vishal. Agrawal",
  "Yagyesh Sahu",
  "Piyush Agrawal",
  "Amit Agrawal",
  "VIMAL CHHUGANI",
  "Manish Rahuja",
  "JASWANT KUMAR",
  "Ankit Agrawal",
  "Amit Gupta",
  "Rohit Yadu",
];
