// Member roster for Victory chapter — Regional Conclave 2026
const MEMBERS = [
  "Aayush Pandey",
  "Abhishek Sharma",
  "Ankit Jain",
  "Arihant Jain",
  "Baldau Tiwari",
  "Chetan Panjwani",
  "Chirag Maru",
  "Deepak Choubey",
  "Devshri Sahu",
  "Harsh Chauhan",
  "Hitesh Patel",
  "Iswar Agrawal",
  "Karan Kumar",
  "Kishan Patel",
  "Kshitiz Pradhan",
  "Lalchand Vatyani",
  "Manik Agrawal",
  "Manish Kumar Jindal",
  "Mayank Dhananjay",
  "Meet Ghodasara",
  "Mitesh Patel",
  "Mrinal Motghare",
  "Mukul Taori",
  "Pankaj Jain",
  "Rishabh Jain",
  "Rohit Kumar",
  "Ronak Patel",
  "Shubham Parikh",
  "Shyam Sharma",
  "Siraj Khan",
  "Sundeep Purwar",
  "Suyash Kumar Singh",
  "Yash Didwania",
  "Akash Tiwari",
  "Shashank Tiwari",
  "Hitesh Sahu",
  "Palash Jain",
  "Nishant Jain",
  "Yash Jain",
  "Darshit Chopda",
];
