// Member roster for Mantra chapter — Regional Conclave 2026
const MEMBERS = [
  "Abhishek Rathore",
  "Amit . Khare",
  "Ammbesh A B Patel",
  "Anam Fatima Pradhan",
  "Anubhuti Raj",
  "ATUL ROHRA",
  "AVIK GHOSH",
  "BHAVYA SACHDEV",
  "Girish Dewangan",
  "Gitika Khatri",
  "HARISH CHAND CHOUHAN",
  "Jatin Khatri",
  "Laxmikant Sahu",
  "Manish Kumar Verma",
  "Murtaza Rafi",
  "Mustufa Ahmed",
  "Naveen Dadsena",
  "Prabhat Tiwari",
  "Sahil Manek",
  "Samarth Singh",
  "Siddhant Shah",
  "Sonal Gupta",
  "Sourabh Jain",
  "Tanuj Gupta",
  "VARDAN CHHABRA",
  "Vasu Sahu",
  "Vikalp Johri",
  "Vinay Jumnani",
  "Vishal Agrawal",
  "Vishal Gupta",
];
