// Member roster for Dynamic chapter — Regional Conclave 2026
const MEMBERS = [
  "ABHISHEK BANSAL",
  "Adarsh Agrawal",
  "Aditya Chopra",
  "Amber Rateria",
  "AMIT AGRAWAL",
  "CHANDAN MOTWANI",
  "Debika Bhattacharya",
  "Deepak Hemani",
  "Divyanshi Sharma",
  "Ginish Pahwa",
  "Gopal Suthar",
  "GUNAKAR KUMAR SAO",
  "JEET AGRAWAL",
  "Johny Jaiswal",
  "Kanha Agrawal",
  "Lakshya Modi",
  "Mohammad Arbaj",
  "Pranav Rateria",
  "Priyanka Patel",
  "Priyash Agrawal",
  "Rahul Agrawal",
  "Sachin Agrawal",
  "Sandesh Garg",
  "SANJU JAGATRAMKA",
  "SANKALP AGRAWAL",
  "Shashank Agrawal",
  "Shiwang Beriwal",
  "SOURABH AGRAWAL",
  "SUMAN RATERIA",
  "Sumeet Sharma",
  "Thakur Shourya Singh",
  "Udit Thawait",
  "VIKASH BERIWAL",
  "Kushal Agrawal",
  "Aayush Pandey",
  "Aditya Agrawal",
  "Suyash Agrawal",
  "JAY SAHU",
  "Ravi Sehgal",
];
