// Member roster for Crystals chapter — Regional Conclave 2026
const MEMBERS = [
  "Aditya Agrawal",
  "AJAY BANSAL",
  "Ajay Jaiswal",
  "AMAN AGRAWAL",
  "Anup Agrawal",
  "Atul Pahuja",
  "Atul Ramani",
  "AVINASH ROCHWANI",
  "AWDHESH AGRAWAL",
  "BOMPADA SAIPRIYA",
  "Chhabi Sahu",
  "Deepak Sahu",
  "Devashish M Kedia",
  "Dhanraj Ramani",
  "DR.SARFARAZ KHAN",
  "Hanish Motwani",
  "JACKY SONI",
  "Ketann Airon",
  "Kishan Gupta",
  "Kunal Motwani",
  "Mukul Jain",
  "NEERAJ . SONI",
  "Pankaj Agrawal",
  "PIYUSH AGRAWAL",
  "PIYUSH SINGH",
  "Prakash Rajpal",
  "Prashant Tiwari",
  "Rahul Dewangan",
  "Rajesh Agrawal",
  "Rishabh Agrawal",
  "Rohit Asrani",
  "SAGAR BATRA",
  "Sagar Kesharwani",
  "Santosh Sahu",
  "SHOURYA AGRAWAL",
  "Shubham Modi",
  "Sumeet Agrawal",
  "Sunil Agrawal",
  "SUNIL RAMANI",
  "Sunil Vishwkarma",
  "USHA SHARMA",
  "Sharvil Sanesar",
  "Deepesh Agrawal",
  "Sarfaraj Ali",
  "Anjani Jhalariya",
  "Nischal Nayyar",
];
