// Member roster for Experts chapter — Regional Conclave 2026
const MEMBERS = [
  "AJAY PRAKASH SHUKLA",
  "Aman Goyal",
  "Amit Agrawal",
  "Anant Srivastav",
  "Arun DAGA",
  "Ayush Parakh",
  "BALMUKUND CHOUBEY",
  "BHASKAR DUTTA MANSANA",
  "Birendra Singh",
  "Deepak Gupta (Lubricants)",
  "DEVRAJ PAL",
  "Gaurav Sahu",
  "Manav Jindal",
  "MANISH. SHARMA",
  "Manoj Kumar Sahu",
  "MITHLESH BHUMARKAR",
  "Nagendra Choudhary",
  "Nikhil Badhai",
  "Parth Chauhan",
  "Prateek Agrawal",
  "Pratik Agrawal",
  "Preeti Sahu",
  "Rahul Agrawal (dry fruits)",
  "Rahul Thethwar",
  "Ritesh Nagwani",
  "Rohit Singh Thakur",
  "RRahul R Modi",
  "Shrikant Parakh",
  "Shubhraj Singh",
  "Shweta Tiwari",
  "Shyam lal Sahu",
  "Sushant Jogdand",
  "Tapan Agrawal",
  "Tarun Gohil",
  "Tribhuvan Sonkar",
  "VIJAY KUMAR SAHU",
  "Vijay Malani",
  "Vivek Yadav",
  "Dr Dharmen Bhansali",
];
