// Member roster for Jupiter chapter — Regional Conclave 2026
const MEMBERS = [
  "Abhinav Gupta",
  "Abhishek Pandey",
  "Ajay Kumar Ratre",
  "Amit Yadu",
  "Anil Kumar",
  "Ankit Agrawal",
  "Ankit Sharma",
  "Ashish Jain",
  "Ashish Pandey",
  "Bhavesh Sahu",
  "Cherag Joshii",
  "Chhatrapal Singh",
  "DEELU SRAVANI",
  "Deepanshu Bansod",
  "Dhanesh Yadu",
  "Dibyendu Saha",
  "FANISH JAIN",
  "Farhan Waliyani",
  "Harsh Vira",
  "Iqbal Ahmed",
  "ITI KESWANI",
  "Jatin Narang",
  "Jitender Singh",
  "Jugal Kishor Prajapati",
  "Kaushlendra Singh Bhuwal",
  "Keertan Vanjhara",
  "Kuber K Chandraker",
  "Manish Paliwal",
  "Manish Kumar Tikariha",
  "Mayank Wadhwa",
  "NEELU SAHU",
  "Neha Rajpal Wadhwa",
  "Nikahat Qureshi",
  "NIKHIL MANDHANIA",
  "Prakash Yadav",
  "Pramod Rajput",
  "Pranav Dubey",
  "Pritesh Raja",
  "Pushp Kashyap",
  "Rahul Jain",
  "Raj Prajapati",
  "Rajat Haldar",
  "RAVI JAGGI",
  "Reetu Sahu",
  "Riju Jain",
  "Rupendra Sahu",
  "Shail Rathore",
  "Shubham Dewangan",
  "Shyam Patidar",
  "Sourabh Tamrakar",
  "Subham Agarwal",
  "Sunny Dodeja",
  "Sunny Sharma",
  "Supriya Diwan",
  "Suraj Das",
  "Suyash Agrawal",
  "Uma Sharma",
  "Utkarsh Pandey",
  "Venugopal Tamrakar",
  "VIJAY JAIN KASTURE",
  "Vikas Gupta",
  "Vinay Patel",
  "Vishay Tiwari",
  "Yudhisthir Pradhan",
  "Ankush Bharti",
  "Nisha Kesharwani",
  "Saurabh Ghosh",
  "Khushboo Verma",
];
