// Member roster for Phoenix chapter — Regional Conclave 2026
const MEMBERS = [
  "Aadit Chopda",
  "Aayush Vaswani",
  "AKASH PATHAK",
  "AKASH SEN SHARMA",
  "Akshay Kumar Sahu",
  "Amol Agrawal",
  "ANGAD SINGH BHATIA",
  "Animesh Sharma",
  "Ankush Pritwani",
  "Ashish Singh",
  "Ashwin Agase",
  "Ayush Jhaveri",
  "BHAVIN PATEL",
  "BHOOPENDRA KUMAR SAHU",
  "CA GITA Sodha",
  "Deepak Pancheshwar",
  "Dheeraj Sen",
  "Dinesh Agrawal",
  "Dishant Patel",
  "DISHI CHHUGANI",
  "Divesh Sahu",
  "Duleandra Tembhare",
  "Heerendra Singh",
  "Ikkbal Dhamani",
  "ISHWAR SAHU",
  "Jaikishan Sahu",
  "Kapil Sherwani",
  "Kaushal Jaiswal",
  "M Ramprasad Rao",
  "Manish Patel",
  "Manoj Agrawal",
  "Naveen Mandal",
  "Navin Pritwani",
  "Neelansh Kansari",
  "Nikhil Athwani",
  "Pavan Biyani",
  "Pawan Tandon",
  "PRATYKSH AGRAWAL",
  "Prince Sharma",
  "PUSHPA BASANT GUPTA",
  "Rajesh Sherwani",
  "Rupesh Sahu",
  "Ruplal Chouhan",
  "Sandeep Pandey",
  "Sanjay Patel",
  "SAURABH AGRAWAL (CCTV)",
  "SAURABH AGRAWAL (ID-RESI.)",
  "Shailesh Kumar Verma",
  "Shivani Jaiswar",
  "Sneh Patel",
  "Taneshwar Sahu",
  "Umesh lilhare",
  "Utkarsh Sharma",
  "Vidhan Agrawal",
  "Subhi Agrawal",
  "Manisha Sinha",
  "Talvinder Singh",
  "Seema Gyanchandani",
  "Vinay Nishad",
];
